name: SLOT
main: pawarenessc\slot\Main
version: 10.1.6
api: 3
author: PawarenessC
load: POSTWORLD
description: play slot.
commands:
 slot:
  description: "スロットを楽しみましょう"
  usage: "/slot"
 slotui:
  description: "スロットのformです"
  usage: "/slotui"
